### ISSUE TITLE
Further research (Not Issue)

### ISSUE THREAD

**Issue by kli017** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#23]
@stuarteiffert  thanks for the awesome work.  I was wondering have you ever do some further work on Activity Recognition based on 2D pose keypoints as you mentioned in the Further research. such as running, walking etc. I have tried your method on UCF-ARG dataset. The result does not very well. The model is hard to tell the different between carrying, walking and running.

**Comment by stuarteiffert** [comment]
Hi,
I have done a bit on walking using the CASIA dataset (http://www.cbsr.ia.ac.cn/english/Gait%20Databases.asp). I was testing how well person identification using gait only worked. I found that you can reasonably classify between subjects, but you need to use a standardised viewpoint, which doesn't seem practical for real world applications.
I haven't compared running versus walking. How do you normalise the input? Is it offset to just the first frame? It seems that it should be very easy to distinguish given just the rate of change of each keypoint across the frame compared to the total keypoint range (ie height of subject in frame). Is this not the case?

**Comment by kli017** [comment]
I did not normalise the input so the model perform very bad. After that I tried to normalise the input with mean and std of each person and found the result became much better. I also normalised the MHAD dataset that you provided. With normalisation the model can converge much faster and can achieve higher acc in the same epoch.
![6n_acc](https://user-images.githubusercontent.com/14877573/61297330-9daed500-a80e-11e9-8667-e1da85b18640.png)

**Comment by Amith4504** [comment]
Hi , 
@kli017 , @stuarteiffert  I tried to normalize the given data set vectors to the range [0,1] considering the original dataset to be varying between [ 0, 500 ]  (max value 500 was assumed since the values varied between 200 to 400 ) . I used np.interp a NUMPY method for normalization to [0,1] . the test accuracy decreased a lot . Is this normalization correct? . 
Also i have observed the openpose outputs to be normalized too. @stuarteiffert  how come ur dataset contains values varying with values such as 300 or 400 etc . ? 
Can u suggest a good normalization method ?

**Comment by dsunjka** [comment]
Hello, can someone share a good normalization method for this kind of data, please?

**Comment by bhdrozgn** [comment]
@Amith4504 @dsunjka 
Did you manage to find a good normalization method? If so, can you provide?
