### ISSUE TITLE
How can run inference in my own example?

### ISSUE THREAD

**Issue by tringn** [stuarteiffert/RNN-for-Human-Activity-Recognition-using-2D-Pose-Input#5]
Hi @stuarteiffert 
Thanks for your excellent work. 
Can you guide me how to export training model and run inference on my own example (output from openpose)?

**Comment by stuarteiffert** [comment]
Hi Tringn,

You can save, and then restore the trained tensor flow model by creating a tf.train.Saver() instance, and using that to save your model checkpoint. See https://www.tensorflow.org/guide/saved_model for more details. Here's how I would do it:

```
#create saver before training
saver = tf.train.Saver()
retrain = False

#check if you want to retrain or import a saved model
if not retrain:
    saver.restore(sess, "/dataset_path/model.ckpt")
    print("Model restored.")

# code to run inference...

# Check if you want to save your current model
if retrain:
    save_path = saver.save(sess, "/save_path/model.ckpt")
    print("Model saved in file: %s" % save_path)
```

Running inference on your own output from openpose is straightforward if you don't need it realtime (ie running from a camera). It's simply a matter of converting the json output of openpose to the same format as the X input I used (see def load_X and the readme. NOTE: I think openpose format has changed sltighly since I lasted worked on this) then running the below after loading your trained model:

```
        X_val = load_X(test_file)
        preds = sess.run(
            [pred],
            feed_dict={
                x: X_val
           }
        )
```

Working from a camera or video is much trickier. The way I have done it in the past is by using the openpose c++ example /openpose/examples/openpose/openpose.cpp (in the openpose package) which works out of the box on video or cameras, and grabbing the output from there, then using the ROS framework and streaming the output of openpose to a python script using the above trained and save model. Let me know how you go after giving it a go.

Stu

**Comment by tringn** [comment]
Thanks so much, Stu. It worked.

**Comment by tringn** [comment]
Thanks so much, Stu. It worked.

**Comment by kli017** [comment]
@tringn Hello, I have some problem to restore the model after training. Could you show me a simple example how you run your inference？

**Comment by arvindchandel** [comment]
@kli017 @tringn @stuarteiffert Hello guys..I am trying to restore the model like below: 
with tf.Session() as sess:
  new_saver = tf.train.import_meta_graph('model.ckpt.meta')
  new_saver.restore(sess, tf.train.latest_checkpoint('./'))

Now when i am trying to run the sess on new sample, 
preds = sess.run( [pred], feed_dict={ x: X_val }
i am getting error pred not defined, i.e network is not loading.
I think i am unable to properly load the model. Plz suggest the changes.

**Comment by arvindchandel** [comment]
Fixed it.
